services:
  - type: web
    name: tx-sentiment-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: COMPOSIO_API_KEY
        value: ak_cdwQZVwTOel5YxPz9BgL
      - key: USE_MOCK
        value: "false"
      - key: NODE_ENV
        value: production
      - key: UPSTASH_REDIS_REST_URL
        value: "https://sincere-sole-53415.upstash.io"
      - key: UPSTASH_REDIS_REST_TOKEN
        value: "AdCnAAIncDE1NTBkOGVlN2I2ZDg0Yjk2OTE2MjdiNWM2YzY0YjE4NXAxNTM0MTU"
